services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount your project folder into the container for live reloading
    environment:
      - ENVIRONMENT=development  # You can define your environment variables here
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
